spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/data
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
server:
  port: 8001
